# Generated by Django 6.0.6 on 2026-07-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_alter_emailmessage_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpconfig',
            name='last_tested',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
