# Generated by Django 6.0.6 on 2026-07-24 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('module', models.CharField(choices=[('contacts', 'Contacts'), ('companies', 'Companies'), ('leads', 'Leads'), ('deals', 'Deals'), ('tasks', 'Tasks'), ('campaigns', 'Campaigns'), ('emails', 'Emails'), ('calendar', 'Calendar'), ('workflows', 'Workflows'), ('ai', 'AI Assistant'), ('system', 'System')], default='system', max_length=50)),
                ('icon', models.CharField(default='fa-info-circle', max_length=50)),
                ('color', models.CharField(default='#6C63FF', max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, default='', max_length=255)),
                ('detail_url', models.CharField(blank=True, default='', max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='activities__user_id_6e81e8_idx'), models.Index(fields=['user', 'module'], name='activities__user_id_6a4819_idx'), models.Index(fields=['user', 'activity_type'], name='activities__user_id_8d348e_idx')],
            },
        ),
    ]
