# Generated by Django 6.0.6 on 2026-07-18 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_name', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('deal_owner', models.CharField(blank=True, help_text='Sales person responsible', max_length=255)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('INR', 'INR'), ('CAD', 'CAD'), ('AUD', 'AUD')], default='USD', max_length=3)),
                ('stage', models.CharField(choices=[('New', 'New'), ('Qualified', 'Qualified'), ('Proposal Sent', 'Proposal Sent'), ('Negotiation', 'Negotiation'), ('Contract Review', 'Contract Review'), ('Won', 'Won'), ('Lost', 'Lost')], default='New', max_length=20)),
                ('probability', models.IntegerField(default=0, help_text='Probability percentage (0–100)')),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(choices=[('Website', 'Website'), ('Referral', 'Referral'), ('LinkedIn', 'LinkedIn'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Cold Email', 'Cold Email'), ('Event', 'Event'), ('Other', 'Other')], default='Website', max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Medium', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Won', 'Won'), ('Lost', 'Lost')], default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='contacts.contact')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='leads.lead')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
