# Generated by Django 6.0.6 on 2026-07-18 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='deal_owner',
        ),
    ]
