# Generated by Django 6.0.6 on 2026-07-18 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('deals', '0002_remove_deal_deal_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='companies.company'),
        ),
    ]
