# Generated by Django 6.0.6 on 2026-07-08 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('trigger_type', models.CharField(choices=[('contact_created', 'Contact Created'), ('lead_created', 'Lead Created'), ('lead_updated', 'Lead Updated'), ('lead_qualified', 'Lead Status → Qualified'), ('lead_won', 'Lead Status → Won'), ('lead_lost', 'Lead Status → Lost'), ('task_created', 'Task Created'), ('task_completed', 'Task Completed'), ('task_overdue', 'Task Overdue'), ('meeting_created', 'Meeting Created'), ('meeting_finished', 'Meeting Finished'), ('campaign_started', 'Campaign Started'), ('campaign_completed', 'Campaign Completed'), ('scheduled_daily', 'Scheduled — Daily'), ('scheduled_weekly', 'Scheduled — Weekly'), ('scheduled_monthly', 'Scheduled — Monthly')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create_task', 'Create Task'), ('update_task', 'Update Task'), ('send_email', 'Send Email'), ('create_event', 'Create Calendar Event'), ('assign_lead', 'Assign Lead'), ('change_lead_status', 'Change Lead Status'), ('add_tag', 'Add Tag'), ('remove_tag', 'Remove Tag'), ('ai_summary', 'Generate AI Summary'), ('ai_email', 'Generate AI Email'), ('ai_followup', 'Generate AI Follow-up'), ('create_notification', 'Create Notification'), ('webhook', 'Webhook (Custom)')], max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='workflows.workflow')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='workflows.workflow')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('time', models.TimeField()),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Required for weekly schedules.', null=True)),
                ('day_of_month', models.IntegerField(blank=True, help_text='Required for monthly schedules (1-31).', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='workflows.workflow')),
            ],
            options={
                'ordering': ['schedule_type', 'time'],
            },
        ),
    ]
