# Generated by Django 6.0.6 on 2026-07-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='trigger_type',
            field=models.CharField(choices=[('contact_created', 'Contact Created'), ('contact_updated', 'Contact Updated'), ('lead_created', 'Lead Created'), ('lead_updated', 'Lead Updated'), ('lead_qualified', 'Lead Status → Qualified'), ('lead_won', 'Lead Status → Won'), ('lead_lost', 'Lead Status → Lost'), ('task_created', 'Task Created'), ('task_completed', 'Task Completed'), ('task_overdue', 'Task Overdue'), ('meeting_created', 'Meeting Created'), ('meeting_finished', 'Meeting Finished'), ('meeting_reminder', 'Meeting Reminder'), ('campaign_created', 'Campaign Created'), ('campaign_started', 'Campaign Started'), ('campaign_completed', 'Campaign Completed'), ('scheduled_daily', 'Scheduled — Daily'), ('scheduled_weekly', 'Scheduled — Weekly'), ('scheduled_monthly', 'Scheduled — Monthly')], max_length=50),
        ),
        migrations.AlterField(
            model_name='workflowaction',
            name='action_type',
            field=models.CharField(choices=[('create_task', 'Create Task'), ('update_task', 'Update Task'), ('send_email', 'Send Email'), ('create_event', 'Create Calendar Event'), ('assign_lead', 'Assign Lead'), ('change_lead_status', 'Change Lead Status'), ('add_tag', 'Add Tag'), ('remove_tag', 'Remove Tag'), ('ai_summary', 'Generate AI Summary'), ('ai_email', 'Generate AI Email'), ('ai_followup', 'Generate AI Follow-up'), ('create_notification', 'Create Notification'), ('send_notification', 'Send Notification'), ('create_contact', 'Create Contact'), ('create_lead', 'Create Lead'), ('create_calendar_event', 'Create Calendar Event'), ('webhook', 'Webhook (Custom)')], max_length=50),
        ),
    ]
