# Generated by Django 6.0.6 on 2026-07-18 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/')),
                ('industry', models.CharField(blank=True, choices=[('Technology', 'Technology'), ('Healthcare', 'Healthcare'), ('Finance', 'Finance'), ('Education', 'Education'), ('Manufacturing', 'Manufacturing'), ('Retail', 'Retail'), ('Real Estate', 'Real Estate'), ('Consulting', 'Consulting'), ('Media', 'Media'), ('Telecommunications', 'Telecommunications'), ('Transportation', 'Transportation'), ('Energy', 'Energy'), ('Hospitality', 'Hospitality'), ('Agriculture', 'Agriculture'), ('Other', 'Other')], default='Other', max_length=50)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('employees', models.IntegerField(blank=True, help_text='Number of employees', null=True)),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('company_size', models.CharField(blank=True, choices=[('1-10', '1-10'), ('11-50', '11-50'), ('51-200', '51-200'), ('201-500', '201-500'), ('501-1000', '501-1000'), ('1001-5000', '1001-5000'), ('5001-10000', '5001-10000'), ('10000+', '10000+')], default='1-10', max_length=20)),
                ('linkedin_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Lead', 'Lead'), ('Prospect', 'Prospect'), ('Customer', 'Customer'), ('Partner', 'Partner'), ('Former', 'Former')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['-created_at'],
            },
        ),
    ]
