# Generated by Django 6.0.6 on 2026-07-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Campaign budget', max_digits=12, null=True),
        ),
    ]
